### PR TITLE
.net standard/core .net framework support

### PR DESCRIPTION
**Pull request by ghost1face**
Added support for .net4.0 -> .net 4.7,  netstandard2.0, netcoreapp2.0.  If you want to create another branch on your side I can redirect this pull request to that branch instead of master for validation

### CODE REVIEW

**Comment by RobThree** [comment]
Thank you very much. I am currently not in a position to do something with this (unexpectedly hospitalized; nothing too bad though) so I will need to get back to you ad soon as I can. Sorry for the inconvenience.

**Comment by ghost1face** [comment]
No problem, hope you get better.  Saw the open issue and figure I contribute.  I'm sure more will need this eventually.  Talk soon

**Comment by ghost1face** [comment]
Just saw activity on this project and wondering if you've had a chance to review.

**Comment by RobThree** [comment]
Well, the AppVeyor build fails now (not a biggie, it fails on building the helpfile) which I'd like to fix and I'll try to look over the PR asap.

**Comment by RobThree** [comment]
> If you want to create another branch on your side I can redirect this pull request to that branch instead of master for validation

I created a branch: `netcore-and-netstandard-support`

**Comment by ghost1face** [comment]
No problem, I'll get it done and get back to you shortly

**Comment by ghost1face** [comment]
Updated the branch with the latest changes from your last commits.  Redirected to new branch

**Comment by RobThree** [comment]
V1.2.20 should support netcore and netstandard. Thanks for the work! 👍

**Pull request merged**
